name: CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Install dependencies
        run: yarn install
      - name: Build website
        run: yarn build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.FRONTENDWIZ_GITHUB_TOKEN }}
          publish_dir: ./build
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com

  run-algolia-crawler:
    name: Run Algolia Crawler
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Docker Script
        run: |
          docker run \
            -e CONFIG="$(cat ./config.json)" \
            -e APPLICATION_ID="${{ secrets.ALGOLIA_APP_ID }}" \
            -e API_KEY="${{ secrets.ALGOLIA_API_KEY }}" \
            algolia/docsearch-scraper
